### ISSUE TITLE
create cart comm line 60

### ISSUE THREAD

**Issue by RoeAshkenazi** [Dreamest/Parallel-Programming---ShearSort#1]
hi man,
first let me tell you  taht you are the best,
you save me with that one.
only one thing,
why in line 60 when you create the cart comm uts not only by the root?
in your code every proccess will run this creat cart comm?
is that Intentionally made?
thx.

**Comment by Dreamest** [comment]
Hey Roe, 

This is a rather old project I did during my studies, but after refreshing my memory, I believe that this is how it's supposed to happen.
If you look into the documentation of [MPI_Cart_create](https://www.mpich.org/static/docs/v3.2.1/www3/MPI_Cart_create.html) and [MPI_Cart_coords](https://www.mpich.org/static/docs/latest/www3/MPI_Cart_coords.html), used in lines 132 and 133 respectively, you'll note that MPI_Cart_coords requires both the rank of the current process and the comm itself, thus all processes should be aware of it.


Best regards,
Dreamest
